version: 1.0.{build}

image: macos-sonoma

environment:
  matrix:
    - CONFIGURATION: Release

before_build:
  - brew update
  - brew install cmake
  - brew install python

build_script:
  - ulimit -n 65536
  - ulimit -c unlimited
  - python3.12 -m venv .
  - source bin/activate
  - python3.12 -m pip install setuptools
  - ./tools/ios_framework_prepare.sh arm64

artifacts:
  - path: build/*.dmg
    name: MyApp
